<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
<meta name="viewport" content="width=device-width">
<meta name="theme-color" content="#222"><meta name="generator" content="Hexo 6.3.0">

  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png">
  <link rel="mask-icon" href="/images/logo.svg" color="#222">

<link rel="stylesheet" href="/css/main.css">



<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha256-/4UQcSmErDzPCMAiuOiWPVVsNN2s3ZY/NsmXNcj0IFc=" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.1.1/animate.min.css" integrity="sha256-PR7ttpcvz8qrF57fur/yAx1qXMFJeJFiA6pSzWi0OIE=" crossorigin="anonymous">

<script class="next-config" data-name="main" type="application/json">{"hostname":"lisiting.net","root":"/","images":"/images","scheme":"Gemini","darkmode":false,"version":"8.15.0","exturl":false,"sidebar":{"position":"left","display":"post","padding":18,"offset":12},"copycode":{"enable":true,"style":"flat"},"bookmark":{"enable":false,"color":"#222","save":"auto"},"mediumzoom":false,"lazyload":false,"pangu":false,"comments":{"style":"tabs","active":null,"storage":true,"lazyload":false,"nav":null},"stickytabs":false,"motion":{"enable":true,"async":false,"transition":{"menu_item":"fadeInDown","post_block":"fadeIn","post_header":"fadeInDown","post_body":"fadeInDown","coll_header":"fadeInLeft","sidebar":"fadeInUp"}},"prism":false,"i18n":{"placeholder":"搜索...","empty":"没有找到任何搜索结果：${query}","hits_time":"找到 ${hits} 个搜索结果（用时 ${time} 毫秒）","hits":"找到 ${hits} 个搜索结果"}}</script><script src="/js/config.js"></script>

    <meta name="description" content="Sometimes Blogging">
<meta property="og:type" content="website">
<meta property="og:title" content="无佛处">
<meta property="og:url" content="http://lisiting.net/index.html">
<meta property="og:site_name" content="无佛处">
<meta property="og:description" content="Sometimes Blogging">
<meta property="og:locale" content="zh_CN">
<meta property="article:author" content="李有时">
<meta property="article:tag" content="Revit, C#, BIM, Dynamo">
<meta name="twitter:card" content="summary">


<link rel="canonical" href="http://lisiting.net/">



<script class="next-config" data-name="page" type="application/json">{"sidebar":"","isHome":true,"isPost":false,"lang":"zh-CN","comments":"","permalink":"","path":"index.html","title":""}</script>

<script class="next-config" data-name="calendar" type="application/json">""</script>
<title>无佛处</title>
  








  <noscript>
    <link rel="stylesheet" href="/css/noscript.css">
  </noscript>
</head>

<body itemscope itemtype="http://schema.org/WebPage" class="use-motion">
  <div class="headband"></div>

  <main class="main">
    <div class="column">
      <header class="header" itemscope itemtype="http://schema.org/WPHeader"><div class="site-brand-container">
  <div class="site-nav-toggle">
    <div class="toggle" aria-label="切换导航栏" role="button">
        <span class="toggle-line"></span>
        <span class="toggle-line"></span>
        <span class="toggle-line"></span>
    </div>
  </div>

  <div class="site-meta">

    <a href="/" class="brand" rel="start">
      <i class="logo-line"></i>
      <h1 class="site-title">无佛处</h1>
      <i class="logo-line"></i>
    </a>
      <p class="site-subtitle" itemprop="description">知者不言，言者不知</p>
  </div>

  <div class="site-nav-right">
    <div class="toggle popup-trigger" aria-label="搜索" role="button">
    </div>
  </div>
</div>



<nav class="site-nav">
  <ul class="main-menu menu"><li class="menu-item menu-item-home"><a href="/" rel="section"><i class="fa fa-home fa-fw"></i>首页</a></li><li class="menu-item menu-item-tags"><a href="/tags/" rel="section"><i class="fa fa-tags fa-fw"></i>标签</a></li><li class="menu-item menu-item-archives"><a href="/archives/" rel="section"><i class="fa fa-archive fa-fw"></i>归档</a></li>
  </ul>
</nav>




</header>
        
  
  <aside class="sidebar">

    <div class="sidebar-inner sidebar-overview-active">
      <ul class="sidebar-nav">
        <li class="sidebar-nav-toc">
          文章目录
        </li>
        <li class="sidebar-nav-overview">
          站点概览
        </li>
      </ul>

      <div class="sidebar-panel-container">
        <!--noindex-->
        <div class="post-toc-wrap sidebar-panel">
        </div>
        <!--/noindex-->

        <div class="site-overview-wrap sidebar-panel">
          <div class="site-author animated" itemprop="author" itemscope itemtype="http://schema.org/Person">
  <p class="site-author-name" itemprop="name">李有时</p>
  <div class="site-description" itemprop="description">Sometimes Blogging</div>
</div>
<div class="site-state-wrap animated">
  <nav class="site-state">
      <div class="site-state-item site-state-posts">
        <a href="/archives/">
          <span class="site-state-item-count">5</span>
          <span class="site-state-item-name">日志</span>
        </a>
      </div>
      <div class="site-state-item site-state-tags">
          <a href="/tags/">
        <span class="site-state-item-count">4</span>
        <span class="site-state-item-name">标签</span></a>
      </div>
  </nav>
</div>

        </div>
      </div>
        <div class="back-to-top animated" role="button" aria-label="返回顶部">
          <i class="fa fa-arrow-up"></i>
          <span>0%</span>
        </div>
    </div>

    
  </aside>


    </div>

    <div class="main-inner index posts-expand">

    


<div class="post-block">
  
  

  <article itemscope itemtype="http://schema.org/Article" class="post-content" lang="">
    <link itemprop="mainEntityOfPage" href="http://lisiting.net/2023/08/08/Dynamo-%E5%85%B3%E4%BA%8E%E5%8F%82%E6%95%B0%E8%B5%8B%E5%80%BC/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="image" content="/images/avatar.gif">
      <meta itemprop="name" content="李有时">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="无佛处">
      <meta itemprop="description" content="Sometimes Blogging">
    </span>

    <span hidden itemprop="post" itemscope itemtype="http://schema.org/CreativeWork">
      <meta itemprop="name" content="undefined | 无佛处">
      <meta itemprop="description" content="">
    </span>
      <header class="post-header">
        <h2 class="post-title" itemprop="name headline">
          <a href="/2023/08/08/Dynamo-%E5%85%B3%E4%BA%8E%E5%8F%82%E6%95%B0%E8%B5%8B%E5%80%BC/" class="post-title-link" itemprop="url">Dynamo-关于参数赋值</a>
        </h2>

        <div class="post-meta-container">
          <div class="post-meta">
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-calendar"></i>
      </span>
      <span class="post-meta-item-text">发表于</span>

      <time title="创建时间：2023-08-08 19:57:52" itemprop="dateCreated datePublished" datetime="2023-08-08T19:57:52+08:00">2023-08-08</time>
    </span>
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-calendar-check"></i>
      </span>
      <span class="post-meta-item-text">更新于</span>
      <time title="修改时间：2023-08-11 05:54:58" itemprop="dateModified" datetime="2023-08-11T05:54:58+08:00">2023-08-11</time>
    </span>

  
</div>

        </div>
      </header>

    
    
    
    <div class="post-body" itemprop="articleBody">
          <p>写写关于Dynamo参数赋值</p>
<h3 id="为单个对象赋单个参数值"><a href="#为单个对象赋单个参数值" class="headerlink" title="为单个对象赋单个参数值"></a>为单个对象赋单个参数值</h3><img src="/2023/08/08/Dynamo-%E5%85%B3%E4%BA%8E%E5%8F%82%E6%95%B0%E8%B5%8B%E5%80%BC/%E6%99%AE%E9%80%9A%E5%81%9A%E6%B3%95.png" class="" title="典型设置">

<p>最容易理解，SetParameterByName需要输入三个参数，元素对象（数据类型：Element），参数名称（数据类型：String），参数值（数据类型：None&#x2F;Integer&#x2F;Double&#x2F;String&#x2F;Element)</p>
<blockquote>
<p>注意，输入的参数值的数据类型需要与指向的参数相符，例如指向的参数需要输入布尔值，如果输入了字符串则会报错</p>
</blockquote>
<h3 id="为单个对象赋多个参数值"><a href="#为单个对象赋多个参数值" class="headerlink" title="为单个对象赋多个参数值"></a>为单个对象赋多个参数值</h3><p>两种方法，第一种是直接在后面加SetParameterByName节点，如果只是修改两个参数，这样操作最快，复制改改输入就好</p>
<img src="/2023/08/08/Dynamo-%E5%85%B3%E4%BA%8E%E5%8F%82%E6%95%B0%E8%B5%8B%E5%80%BC/%E5%8D%95%E5%AF%B9%E8%B1%A1%E5%A4%9A%E5%8F%82%E6%95%B01.png" class="" title="单对象多参数1">

<p>如果修改的参数多，可以给SetParameterByName输入参数列表及值列表，要注意列表项要一一对应</p>
<img src="/2023/08/08/Dynamo-%E5%85%B3%E4%BA%8E%E5%8F%82%E6%95%B0%E8%B5%8B%E5%80%BC/%E5%8D%95%E5%AF%B9%E8%B1%A1%E5%A4%9A%E5%8F%82%E6%95%B02.png" class="" title="单对象多参数2">

<h3 id="为多个对象各赋单个参数值"><a href="#为多个对象各赋单个参数值" class="headerlink" title="为多个对象各赋单个参数值"></a>为多个对象各赋单个参数值</h3><p>当多个对象的参数值都是一样的时候，实现很简单，直接往SetParameterByName传入element列表就好</p>
<img src="/2023/08/08/Dynamo-%E5%85%B3%E4%BA%8E%E5%8F%82%E6%95%B0%E8%B5%8B%E5%80%BC/%E5%A4%9A%E5%AF%B9%E8%B1%A1%E5%8D%95%E5%8F%82%E6%95%B0.png" class="" title="多对象单参数">

<p>如果多个对象的参数值有可能不一样，可将参数值作为列表输入</p>
<img src="/2023/08/08/Dynamo-%E5%85%B3%E4%BA%8E%E5%8F%82%E6%95%B0%E8%B5%8B%E5%80%BC/%E5%A4%9A%E5%AF%B9%E8%B1%A1%E5%8D%95%E5%8F%82%E6%95%B01.png" class="" title="多对象单参数1">

<h3 id="为多个对象各赋多个参数值"><a href="#为多个对象各赋多个参数值" class="headerlink" title="为多个对象各赋多个参数值"></a>为多个对象各赋多个参数值</h3><p>这种情况列表结构开始复杂，但也是业务中最常碰到的场景</p>
<img src="/2023/08/08/Dynamo-%E5%85%B3%E4%BA%8E%E5%8F%82%E6%95%B0%E8%B5%8B%E5%80%BC/%E5%A4%9A%E5%AF%B9%E8%B1%A1%E5%A4%9A%E5%8F%82%E6%95%B0.png" class="" title="多对象多参数">

<h3 id="使用Python-Script节点实现"><a href="#使用Python-Script节点实现" class="headerlink" title="使用Python Script节点实现"></a>使用Python Script节点实现</h3><p>也可以用python自定义一个节点，那样不管哪种情况拿起直接用就好</p>
<p>核心方法就是将参数与参数值的输入都处理成二维列表，然后用统一的遍历逻辑进行参数写入</p>
<p>下面代码</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># 导入所需的模块</span></span><br><span class="line"><span class="keyword">import</span> clr</span><br><span class="line">clr.AddReference(<span class="string">&#x27;RevitAPI&#x27;</span>)</span><br><span class="line">clr.AddReference(<span class="string">&#x27;RevitAPIUI&#x27;</span>)</span><br><span class="line"><span class="keyword">from</span> Autodesk.Revit.DB <span class="keyword">import</span> *</span><br><span class="line"><span class="keyword">from</span> RevitServices.Persistence <span class="keyword">import</span> DocumentManager</span><br><span class="line"><span class="keyword">from</span> RevitServices.Transactions <span class="keyword">import</span> TransactionManager</span><br><span class="line"></span><br><span class="line"><span class="comment"># 获取Dynamo中的Revit文档</span></span><br><span class="line">doc = DocumentManager.Instance.CurrentDBDocument</span><br><span class="line"></span><br><span class="line"><span class="comment"># 元素</span></span><br><span class="line">elements = UnwrapElement(IN[<span class="number">0</span>]) <span class="keyword">if</span> <span class="built_in">isinstance</span>(IN[<span class="number">0</span>], <span class="built_in">list</span>) <span class="keyword">else</span> [UnwrapElement(IN[<span class="number">0</span>])]</span><br><span class="line"></span><br><span class="line"><span class="comment"># 参数</span></span><br><span class="line">input_parameters = IN[<span class="number">1</span>]</span><br><span class="line"></span><br><span class="line"><span class="comment"># 值</span></span><br><span class="line">input_values = IN[<span class="number">2</span>]</span><br><span class="line"></span><br><span class="line"><span class="comment"># 统一输入</span></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">process_input</span>(<span class="params">input_data, elements_count</span>):</span><br><span class="line">    dimensions = get_list_dimensions(input_data)</span><br><span class="line">    </span><br><span class="line">    <span class="keyword">if</span> <span class="keyword">not</span> dimensions:  <span class="comment"># 非列表情况，将元素包含到一个二维列表中</span></span><br><span class="line">        <span class="keyword">return</span> [[input_data] <span class="keyword">for</span> _ <span class="keyword">in</span> <span class="built_in">range</span>(elements_count)]</span><br><span class="line">    <span class="keyword">elif</span> <span class="built_in">len</span>(dimensions) == <span class="number">1</span>:  <span class="comment"># 一维列表情况，重复一维列表成为二维列表</span></span><br><span class="line">        <span class="keyword">return</span> [input_data] * elements_count</span><br><span class="line">    <span class="keyword">elif</span> <span class="built_in">len</span>(dimensions) == <span class="number">2</span>:  <span class="comment"># 二维列表情况</span></span><br><span class="line">        <span class="keyword">return</span> input_data</span><br><span class="line">    <span class="keyword">else</span>:</span><br><span class="line">        <span class="keyword">raise</span> ValueError(<span class="string">&quot;检查输入数据的维度&quot;</span>)</span><br><span class="line"></span><br><span class="line"><span class="comment"># 修改参数</span></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">modify_parameter</span>(<span class="params">element, parameter, value</span>):</span><br><span class="line">    param = element.LookupParameter(parameter)</span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> param:</span><br><span class="line">        <span class="keyword">try</span>:</span><br><span class="line">            TransactionManager.Instance.EnsureInTransaction(doc)</span><br><span class="line">            param.<span class="type">Set</span>(value)</span><br><span class="line">            TransactionManager.Instance.TransactionTaskDone()</span><br><span class="line">            <span class="keyword">return</span> element</span><br><span class="line">        <span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">            TransactionManager.Instance.TransactionTaskDone()</span><br><span class="line">            <span class="keyword">return</span> <span class="literal">None</span></span><br><span class="line">    <span class="keyword">else</span>:</span><br><span class="line">        <span class="keyword">return</span> <span class="literal">None</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># 获取列表的维度</span></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">get_list_dimensions</span>(<span class="params">ls</span>):</span><br><span class="line">    <span class="keyword">if</span> <span class="built_in">isinstance</span>(ls, <span class="built_in">list</span>):</span><br><span class="line">        <span class="keyword">return</span> [<span class="built_in">len</span>(ls)] + get_list_dimensions(ls[<span class="number">0</span>])</span><br><span class="line">    <span class="keyword">else</span>:</span><br><span class="line">        <span class="keyword">return</span> []</span><br><span class="line"></span><br><span class="line"><span class="comment"># 检查参数与参数值数量是否一致</span></span><br><span class="line"><span class="keyword">def</span> <span class="title function_">check_matching_lengths</span>(<span class="params">parameters, values</span>):</span><br><span class="line">    flattened_parameters = [item <span class="keyword">for</span> sublist <span class="keyword">in</span> parameters <span class="keyword">for</span> item <span class="keyword">in</span> sublist]</span><br><span class="line">    flattened_values = [item <span class="keyword">for</span> sublist <span class="keyword">in</span> values <span class="keyword">for</span> item <span class="keyword">in</span> sublist]</span><br><span class="line">    <span class="keyword">if</span> <span class="built_in">len</span>(flattened_parameters) != <span class="built_in">len</span>(flattened_values):</span><br><span class="line">        <span class="keyword">raise</span> ValueError(<span class="string">&quot;参数与参数值的数量未对应&quot;</span>)</span><br><span class="line"></span><br><span class="line">output = []</span><br><span class="line">modified_elements = <span class="built_in">set</span>()</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    parameters = process_input(input_parameters, <span class="built_in">len</span>(elements)) <span class="comment"># 1) 处理参数输入</span></span><br><span class="line">    values = process_input(input_values, <span class="built_in">len</span>(elements)) <span class="comment"># 2) 处理值输入</span></span><br><span class="line">    check_matching_lengths(parameters, values) <span class="comment"># 3) 检查数量是否一致</span></span><br><span class="line">    <span class="keyword">for</span> element, element_params, element_values <span class="keyword">in</span> <span class="built_in">zip</span>(elements, parameters, values):<span class="comment">#4) 修改</span></span><br><span class="line">        <span class="keyword">for</span> parameter, value <span class="keyword">in</span> <span class="built_in">zip</span>(element_params, element_values):</span><br><span class="line">            modified_element = modify_parameter(element, parameter, value)</span><br><span class="line">            <span class="keyword">if</span> modified_element <span class="keyword">and</span> modified_element <span class="keyword">not</span> <span class="keyword">in</span> modified_elements:</span><br><span class="line">                output.append(modified_element)</span><br><span class="line">                modified_elements.add(modified_element)</span><br><span class="line"><span class="keyword">except</span> ValueError <span class="keyword">as</span> ve:</span><br><span class="line">    output.append(<span class="built_in">str</span>(ve))</span><br><span class="line">        </span><br><span class="line">OUT = output</span><br></pre></td></tr></table></figure>

<h3 id="为实例对象的类型参数赋值"><a href="#为实例对象的类型参数赋值" class="headerlink" title="为实例对象的类型参数赋值"></a>为实例对象的类型参数赋值</h3><p>见过很多次初学者都提出过的赋值问题，由于对实例和类型理解得不深刻，不知道如何为类型赋值</p>
<p>逻辑很简单，获取到实例后，先由实例获取到类型，然后再对类型的参数做修改</p>
<img src="/2023/08/08/Dynamo-%E5%85%B3%E4%BA%8E%E5%8F%82%E6%95%B0%E8%B5%8B%E5%80%BC/%E7%B1%BB%E5%9E%8B%E5%8F%82%E6%95%B0.png" class="" title="类型参数">

<blockquote>
<p>注意，修改类型参数会将修改影响到所有相关的实例</p>
</blockquote>
<h3 id="遇过的一些坑"><a href="#遇过的一些坑" class="headerlink" title="遇过的一些坑"></a>遇过的一些坑</h3><p><strong>重复名称的参数</strong></p>
<p>一些情况下，一个实例可能出现名称一样的两个参数，仅通过参数名称，可能会指向错误的参数</p>
<img src="/2023/08/08/Dynamo-%E5%85%B3%E4%BA%8E%E5%8F%82%E6%95%B0%E8%B5%8B%E5%80%BC/%E9%87%8D%E5%A4%8D%E5%8F%82%E6%95%B01.png" class="" title="自定义参数重复">

<img src="/2023/08/08/Dynamo-%E5%85%B3%E4%BA%8E%E5%8F%82%E6%95%B0%E8%B5%8B%E5%80%BC/%E9%87%8D%E5%A4%8D%E5%8F%82%E6%95%B02.png" class="" title="自带参数重复">

<p>对于这种情况，通常需要增加更多的判断条件，例如是否软件自带参数，是否共享参数，甚至直接使用固定的ID等，才可以指向准确的参数</p>
<p><strong>错误的参数类型</strong></p>
<p>基础却又容易忽略的问题，当需要修改的参数很多的时候，时常会忽略了参数的类型</p>
<p>有一次跑脚本发现一直抱错，排除半天才发现居然忽略了这个基础问题</p>
<p>而有时一些参数的命名又容易让人产生误导，例如一个命名为“长度”的自定义参数，输入实际上被设置为字符串（有意或无意），而调试时容易将其理解为数值，导致输入错误</p>
<p>所以还是要注意输入的参数类型</p>
<p><strong>不要在生产项目中调试数据</strong></p>
<p>关于数据的写入，如果出现了错误，有时会非常隐蔽，</p>
<p>常见的情况是调试的时候往A参数写了数据，后续可能又将脚本修改调整到了其他参数，但此时A参数上的数据并没有被清除或回撤，如果这个是生产项目，而A参数后续又会被用到其他地方，则可能带来一些不可预料的影响</p>
<p>所以在编写及调试脚本的时候，不要直接在生产项目中进行</p>
<hr>
<p>思绪凌乱，失眠严重，前路未卜</p>

      
    </div>

    
    
    

    <footer class="post-footer">
        <div class="post-eof"></div>
      
    </footer>
  </article>
</div>




    


<div class="post-block">
  
  

  <article itemscope itemtype="http://schema.org/Article" class="post-content" lang="">
    <link itemprop="mainEntityOfPage" href="http://lisiting.net/2023/07/16/Unity3d-%E8%B7%AF%E5%BE%84%E5%B7%A1%E9%80%BB/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="image" content="/images/avatar.gif">
      <meta itemprop="name" content="李有时">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="无佛处">
      <meta itemprop="description" content="Sometimes Blogging">
    </span>

    <span hidden itemprop="post" itemscope itemtype="http://schema.org/CreativeWork">
      <meta itemprop="name" content="undefined | 无佛处">
      <meta itemprop="description" content="">
    </span>
      <header class="post-header">
        <h2 class="post-title" itemprop="name headline">
          <a href="/2023/07/16/Unity3d-%E8%B7%AF%E5%BE%84%E5%B7%A1%E9%80%BB/" class="post-title-link" itemprop="url">Unity3d-路径巡逻</a>
        </h2>

        <div class="post-meta-container">
          <div class="post-meta">
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-calendar"></i>
      </span>
      <span class="post-meta-item-text">发表于</span>
      

      <time title="创建时间：2023-07-16 01:34:28 / 修改时间：03:25:14" itemprop="dateCreated datePublished" datetime="2023-07-16T01:34:28+08:00">2023-07-16</time>
    </span>

  
</div>

        </div>
      </header>

    
    
    
    <div class="post-body" itemprop="articleBody">
          <p>使用U3D实现的简单巡逻方法</p>
<ul>
<li>游戏对象逐个向组成路径的节点进行直线移动</li>
<li>两种巡逻方案<ol>
<li>根据列表顺序移动，到达最后一个后，直接返回第一个，重新开始循环</li>
<li>根据列表顺序移动，到达最后一个后，根据顺序反向移动到第一个，重新开始循环</li>
</ol>
</li>
</ul>
<h2 id="巡逻方案1"><a href="#巡逻方案1" class="headerlink" title="巡逻方案1"></a>巡逻方案1</h2><img src="/2023/07/16/Unity3d-%E8%B7%AF%E5%BE%84%E5%B7%A1%E9%80%BB/%E5%B7%A1%E9%80%BB%E6%96%B9%E6%A1%881.gif" class="" title="巡逻方案1">

<p><strong>实现代码</strong></p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> Transform pathNodes;</span><br><span class="line"><span class="keyword">public</span> <span class="built_in">float</span> moveSpeed = <span class="number">5f</span>; <span class="comment">//移动速度</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">private</span> <span class="built_in">int</span> currentNodeIndex = <span class="number">0</span>;<span class="comment">//当前节点位置的索引</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">Start</span>()</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">//初始位置</span></span><br><span class="line">    transform.position = pathNodes.GetChild(<span class="number">0</span>).position;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">Update</span>()</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">//检查是否到达</span></span><br><span class="line">    <span class="keyword">if</span> (Vector3.Distance(transform.position, pathNodes.GetChild(currentNodeIndex).position) &lt; <span class="number">0.1f</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        currentNodeIndex = (currentNodeIndex + <span class="number">1</span>) % pathNodes.childCount;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">//方向</span></span><br><span class="line">    Vector3 targetDirection = pathNodes.GetChild(currentNodeIndex).position - transform.position;</span><br><span class="line">    targetDirection.Normalize();</span><br><span class="line"></span><br><span class="line">    <span class="comment">//移动</span></span><br><span class="line">    transform.position += targetDirection * moveSpeed * Time.deltaTime;</span><br><span class="line">    transform.rotation = Quaternion.LookRotation(targetDirection);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>实现思路</strong></p>
<ol>
<li>首先将对象初始化在起始位置</li>
<li>每帧检查对象是否到达节点，当对象与节点距离小于0.1则判断为到达</li>
<li>到达后将索引号+1，使用%运算让索引号在节点列表中循环</li>
<li>计算方向</li>
<li>旋转对象，朝节点移动</li>
</ol>
<h2 id="巡逻方案2"><a href="#巡逻方案2" class="headerlink" title="巡逻方案2"></a>巡逻方案2</h2><img src="/2023/07/16/Unity3d-%E8%B7%AF%E5%BE%84%E5%B7%A1%E9%80%BB/%E5%B7%A1%E9%80%BB%E6%96%B9%E6%A1%882.gif" class="" title="巡逻方案1">

<p><strong>实现代码</strong></p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> Transform pathNodes;</span><br><span class="line"><span class="keyword">public</span> <span class="built_in">float</span> moveSpeed = <span class="number">5f</span>; <span class="comment">//移动速度</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">private</span> <span class="built_in">int</span> currentNodeIndex = <span class="number">0</span>;<span class="comment">//当前节点位置的索引</span></span><br><span class="line"><span class="keyword">private</span> <span class="built_in">bool</span> isMovingForward = <span class="literal">true</span>; <span class="comment">//是否正向移动</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">Start</span>()</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">//初始位置</span></span><br><span class="line">    transform.position = pathNodes.GetChild(<span class="number">0</span>).position;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">Update</span>()</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">//检查是否到达</span></span><br><span class="line">    <span class="keyword">if</span> (Vector3.Distance(transform.position, pathNodes.GetChild(currentNodeIndex).position) &lt; <span class="number">0.1f</span>)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">//方案1</span></span><br><span class="line">        <span class="comment">//currentNodeIndex = (currentNodeIndex + 1) % pathNodes.childCount;</span></span><br><span class="line"></span><br><span class="line">        <span class="comment">//方案2</span></span><br><span class="line">        <span class="keyword">if</span> (isMovingForward)</span><br><span class="line">        &#123;</span><br><span class="line">            currentNodeIndex++;</span><br><span class="line">            <span class="keyword">if</span> (currentNodeIndex &gt;= pathNodes.childCount)</span><br><span class="line">            &#123;</span><br><span class="line">                currentNodeIndex = pathNodes.childCount - <span class="number">2</span>;</span><br><span class="line">                isMovingForward = <span class="literal">false</span>;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">else</span></span><br><span class="line">        &#123;</span><br><span class="line">            currentNodeIndex--;</span><br><span class="line">            <span class="keyword">if</span> (currentNodeIndex &lt; <span class="number">0</span>)</span><br><span class="line">            &#123;</span><br><span class="line">                currentNodeIndex = <span class="number">1</span>;</span><br><span class="line">                isMovingForward = <span class="literal">true</span>;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="comment">//方向</span></span><br><span class="line">    Vector3 targetDirection = pathNodes.GetChild(currentNodeIndex).position - transform.position;</span><br><span class="line">    targetDirection.Normalize();</span><br><span class="line"></span><br><span class="line">    <span class="comment">//移动</span></span><br><span class="line">    transform.position += targetDirection * moveSpeed * Time.deltaTime;</span><br><span class="line">    transform.rotation = Quaternion.LookRotation(targetDirection);</span><br></pre></td></tr></table></figure>

<p><strong>实现思路</strong></p>
<ol>
<li>首先将对象初始化在起始位置</li>
<li>每帧检查对象是否到达节点，当对象与节点距离小于0.1则判断为到达</li>
<li>添加一个变量记录正向及反向移动，正向时到达节点后将索引号+1，反向时到达节点后索引号-1</li>
<li>计算方向</li>
<li>旋转对象，朝节点移动</li>
</ol>

      
    </div>

    
    
    

    <footer class="post-footer">
        <div class="post-eof"></div>
      
    </footer>
  </article>
</div>




    


<div class="post-block">
  
  

  <article itemscope itemtype="http://schema.org/Article" class="post-content" lang="">
    <link itemprop="mainEntityOfPage" href="http://lisiting.net/2023/06/21/Revit%E8%A7%86%E5%9B%BE%E6%A0%B7%E6%9D%BF%E8%AE%BE%E7%BD%AE-%E6%A0%87%E9%AB%98%E4%B9%8B%E4%B8%8A%E5%8F%8A%E6%A0%87%E9%AB%98%E4%B9%8B%E4%B8%8B/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="image" content="/images/avatar.gif">
      <meta itemprop="name" content="李有时">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="无佛处">
      <meta itemprop="description" content="Sometimes Blogging">
    </span>

    <span hidden itemprop="post" itemscope itemtype="http://schema.org/CreativeWork">
      <meta itemprop="name" content="undefined | 无佛处">
      <meta itemprop="description" content="">
    </span>
      <header class="post-header">
        <h2 class="post-title" itemprop="name headline">
          <a href="/2023/06/21/Revit%E8%A7%86%E5%9B%BE%E6%A0%B7%E6%9D%BF%E8%AE%BE%E7%BD%AE-%E6%A0%87%E9%AB%98%E4%B9%8B%E4%B8%8A%E5%8F%8A%E6%A0%87%E9%AB%98%E4%B9%8B%E4%B8%8B/" class="post-title-link" itemprop="url">Revit视图样板设置-标高之上及标高之下</a>
        </h2>

        <div class="post-meta-container">
          <div class="post-meta">
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-calendar"></i>
      </span>
      <span class="post-meta-item-text">发表于</span>

      <time title="创建时间：2023-06-21 02:37:21" itemprop="dateCreated datePublished" datetime="2023-06-21T02:37:21+08:00">2023-06-21</time>
    </span>
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-calendar-check"></i>
      </span>
      <span class="post-meta-item-text">更新于</span>
      <time title="修改时间：2023-06-22 05:32:16" itemprop="dateModified" datetime="2023-06-22T05:32:16+08:00">2023-06-22</time>
    </span>

  
</div>

        </div>
      </header>

    
    
    
    <div class="post-body" itemprop="articleBody">
          <h2 id="通常做法"><a href="#通常做法" class="headerlink" title="通常做法"></a>通常做法</h2><p>Revit平面相关的视图样板中有一项视图范围的设置，可以设置平面视图套了这个样板后的视图范围。</p>
<p>比较常见的做法是使用<strong>相关标高</strong>设置固定的值。这样不管使用这个视图样板的视图通过哪一个标高创建，都会根据对应的标高设定一个固定的视图范围值。</p>
<p>下图是默认建筑样板的<code>平面_楼层</code>视图样板的视图范围设置，如果某平面视图使用标高2F进行创建，套用这个视图样板后，这个视图就会使用2F偏移2300mm作为视图范围的顶部，2F偏移1100mm作为视图的剖切面，2F偏移0mm作为视图范围底部。</p>
<img src="/2023/06/21/Revit%E8%A7%86%E5%9B%BE%E6%A0%B7%E6%9D%BF%E8%AE%BE%E7%BD%AE-%E6%A0%87%E9%AB%98%E4%B9%8B%E4%B8%8A%E5%8F%8A%E6%A0%87%E9%AB%98%E4%B9%8B%E4%B8%8B/%E5%85%B8%E5%9E%8B%E8%A7%86%E5%9B%BE%E8%8C%83%E5%9B%B4%E8%AE%BE%E7%BD%AE.png" class="" title="典型设置">

<h2 id="标高之上（之下）"><a href="#标高之上（之下）" class="headerlink" title="标高之上（之下）"></a>标高之上（之下）</h2><p>上面的方法有一个问题，如果层高超出了设置的固定值，有可能会导致一些图元超出视图范围，导致在平面中看不见。</p>
<blockquote>
<p>例如视图范围的顶部固定在2300，但实际层高超出了这个值。这时候为了保证图元完整，项目上通常做法是取消样板设置，手动调整视图范围。项目上更极端的会直接调视图样板中的固定值。不管采用前面说的哪个做法，在项目历经多次的修改或者转手多个人后，都有可能因为这个的操作导致视图多一些或者少一些东西。</p>
<p>所以我做项目支持的时候，总是先检查视图范围</p>
</blockquote>
<p>所以我更喜欢使用后面这种设置方案——标高之上（之下）。</p>
<p>通常，我会将视图范围的顶部设置在当前标高的上一个标高。例如当前视图在2F，大部分情况下，视图的顶部应当是3F。</p>
<p>要实现这个想法，首先在样板中，需要将原本顶部的<strong>相关标高</strong>改为<strong>标高之上</strong>，通常，我会将偏移值设置为0。</p>
<img src="/2023/06/21/Revit%E8%A7%86%E5%9B%BE%E6%A0%B7%E6%9D%BF%E8%AE%BE%E7%BD%AE-%E6%A0%87%E9%AB%98%E4%B9%8B%E4%B8%8A%E5%8F%8A%E6%A0%87%E9%AB%98%E4%B9%8B%E4%B8%8B/%E6%A0%87%E9%AB%98%E4%B9%8B%E4%B8%8A.png" class="" title="标高之上">

<p>在样板中设置好后，还需要告知使用样板的人员，要保证创建了标高之上的相关视图。例如对2F的视图应用此样板，则要保证项目中创建了3F的视图。</p>
<p><strong>经测试，在Revit中，判定为标高之上的标高需同时满足以下条件</strong></p>
<ol>
<li>高度大于或等于当前视图的相关标高（如果多个标高比当前标高高，则取最近；如果多个标高与当前标高重叠，则取最先）</li>
<li>此标高已创建相关视图</li>
</ol>
<p>在立面中可以看出哪些标高已经创建了相关平面。下图中1F，2F标高符合呈现蓝色，代表已经创建了相关视图。而3F标高符号为白色，代表未创建相关视图。当1F使用视图样板时，标高之上为2F。当2F使用视图样板时，<strong>无标高之上，视图范围顶部会变为无穷</strong>。</p>
<img src="/2023/06/21/Revit%E8%A7%86%E5%9B%BE%E6%A0%B7%E6%9D%BF%E8%AE%BE%E7%BD%AE-%E6%A0%87%E9%AB%98%E4%B9%8B%E4%B8%8A%E5%8F%8A%E6%A0%87%E9%AB%98%E4%B9%8B%E4%B8%8B/%E5%9C%A8%E7%AB%8B%E9%9D%A2%E4%B8%AD%E6%A3%80%E6%9F%A5.png" class="" title="在立面中检查">

<p>标高之下与标高之上类似，不一样的只是判定的条件变为高度小于等于当前相关标高。</p>
<p>要注意的是仅视图范围顶部有标高之上的选项，而视图范围底部及视图深度有标高之下的选项。剖切面只可以使用相关标高。</p>
<h2 id="碎碎念"><a href="#碎碎念" class="headerlink" title="碎碎念"></a>碎碎念</h2><p>想想我也好久没去调试样板了，今天指导后生的时候，心中十分感慨</p>
<p>以前哪怕当上了部门负责人，也一直冲锋在前，很多事情亲历亲为</p>
<p>以前我总觉得我能干倒一切，我满腔热血，我什么也不怕</p>
<p>不知不觉，我开始指导后来的人，慢慢变成”想当年”了</p>
<p>身体每况愈下，前路却更加飘摇</p>

      
    </div>

    
    
    

    <footer class="post-footer">
        <div class="post-eof"></div>
      
    </footer>
  </article>
</div>




    


<div class="post-block">
  
  

  <article itemscope itemtype="http://schema.org/Article" class="post-content" lang="">
    <link itemprop="mainEntityOfPage" href="http://lisiting.net/2023/04/17/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%B9%8B%E5%88%9B%E5%BB%BA%E5%B9%B6%E5%88%87%E6%8D%A2%E5%88%B0%E6%96%B0%E6%96%87%E6%A1%A3/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="image" content="/images/avatar.gif">
      <meta itemprop="name" content="李有时">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="无佛处">
      <meta itemprop="description" content="Sometimes Blogging">
    </span>

    <span hidden itemprop="post" itemscope itemtype="http://schema.org/CreativeWork">
      <meta itemprop="name" content="undefined | 无佛处">
      <meta itemprop="description" content="">
    </span>
      <header class="post-header">
        <h2 class="post-title" itemprop="name headline">
          <a href="/2023/04/17/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%B9%8B%E5%88%9B%E5%BB%BA%E5%B9%B6%E5%88%87%E6%8D%A2%E5%88%B0%E6%96%B0%E6%96%87%E6%A1%A3/" class="post-title-link" itemprop="url">Revit二次开发之创建并切换到新文档</a>
        </h2>

        <div class="post-meta-container">
          <div class="post-meta">
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-calendar"></i>
      </span>
      <span class="post-meta-item-text">发表于</span>
      

      <time title="创建时间：2023-04-17 05:42:07 / 修改时间：05:42:59" itemprop="dateCreated datePublished" datetime="2023-04-17T05:42:07+08:00">2023-04-17</time>
    </span>

  
</div>

        </div>
      </header>

    
    
    
    <div class="post-body" itemprop="articleBody">
          <h2 id="通常方法"><a href="#通常方法" class="headerlink" title="通常方法"></a>通常方法</h2><p>Revit API 中提供了<code>Application.NewProjectDocument</code>方法用于创建新项目，但这个方法仅在内存中对项目进行创建，Revit的界面并不会将这个项目显示出来。所以通常情况下，创建一个新项目文件需要分为三个步骤</p>
<ol>
<li>使用<code>Application.NewProjectDocument</code>方法在内存中创建项目文档。</li>
<li>将文档进行保存并关闭。</li>
<li>通过<code>OpenAndActivateDocument</code>方法重新打开并激活该项目文档。</li>
</ol>
<p>也就是说，目前在API提供的方法中，需要重新打开文档才能激活成活动文档。</p>
<p>下面的代码片段实现通常方法的项目创建</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line">         	<span class="comment">//创建</span></span><br><span class="line">Document newDoc = uiapp.Application.NewProjectDocument(<span class="string">@&quot;C:\ProgramData\Autodesk\RVT 2016\Templates\China\Construction-DefaultCHSCHS.rte&quot;</span>);</span><br><span class="line">            <span class="comment">//保存后关闭</span></span><br><span class="line">newDoc.SaveAs(filePath);</span><br><span class="line">            newDoc.Close(<span class="literal">false</span>);</span><br><span class="line">            <span class="comment">//重新打开</span></span><br><span class="line">uiapp.OpenAndActivateDocument(filePath);</span><br></pre></td></tr></table></figure>

<h2 id="第二种方法"><a href="#第二种方法" class="headerlink" title="第二种方法"></a>第二种方法</h2><p>经过查阅资料，发现有一种方法可以在不重新打开文档的情况下对活动文档进行切换。API中提供了<code>ShowElements</code>方法，该方法可以打开一个相关视图，以显示输入的元素。利用该方法，传入文档中被显示在某个视图中的一个元素，就可以将该文档切换成活动文档。</p>
<p>在使用<code>ShowElements</code>方法时，如果传入的元素的相关视图都没有被打开，则会弹出一个警告框，需要用户手动确认是否遍历全部视图。如果不想显示该警告框，则需要通过<code>DialogBoxShowing</code>事件来屏蔽该弹窗。</p>
<p>这种切换方法在进行多文档操作时会相对便利，因为使用<code>OpenAndActivateDocument</code>在文档间切换的效率比较低，尤其是在某个文档比较大时。</p>
<p>因此，如果想要创建一个文件并直接切换为活动文档，则可以通过以下步骤实现：</p>
<ol>
<li>使用<code>Application.NewProjectDocument</code>方法在内存中创建项目文档。</li>
<li>临时在一个视图中创建一条详图线（如果使用了特定样板，则可以直接使用样板中的一个确定元素）。</li>
<li>使用<code>ShowElements</code>方法切换文档。</li>
<li>删除临时创建的详图线。</li>
</ol>
<p>下面的代码片段实现了在Revit中创建一个新项目，并直接切换成活动文档</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> Result <span class="title">Execute</span>(<span class="params">ExternalCommandData commandData, <span class="keyword">ref</span> <span class="built_in">string</span> message, ElementSet elements</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    UIApplication uiapp = commandData.Application;</span><br><span class="line"></span><br><span class="line">    uiapp.DialogBoxShowing += Uiapp_DialogBoxShowing;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">var</span> doc = uiapp.Application.NewProjectDocument(UnitSystem.Metric);</span><br><span class="line">    UIDocument uidoc = <span class="keyword">new</span> UIDocument(doc);</span><br><span class="line">    IList&lt;Element&gt; views = <span class="keyword">new</span> FilteredElementCollector(doc).OfClass(<span class="keyword">typeof</span>(ViewPlan)).ToElements();</span><br><span class="line">    ViewPlan viewPlan = views.First() <span class="keyword">as</span> ViewPlan;</span><br><span class="line">    DetailCurve temCurve = <span class="literal">null</span>;</span><br><span class="line">    </span><br><span class="line">    <span class="comment">//临时事件</span></span><br><span class="line">    <span class="keyword">using</span> (TransactionGroup transactionGroup = <span class="keyword">new</span> TransactionGroup(doc, <span class="string">&quot;temTransationGroup&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        transactionGroup.Start();</span><br><span class="line"></span><br><span class="line">        <span class="keyword">using</span> (Transaction tran = <span class="keyword">new</span> Transaction(doc, <span class="string">&quot;command1&quot;</span>))</span><br><span class="line">        &#123;</span><br><span class="line">            tran.Start();</span><br><span class="line">            temCurve = doc.Create.NewDetailCurve(viewPlan, Line.CreateBound(<span class="keyword">new</span> XYZ(), <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">100</span>, <span class="number">0</span>)));</span><br><span class="line">            tran.Commit();</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        uidoc.ShowElements(temCurve);</span><br><span class="line"></span><br><span class="line">        <span class="keyword">using</span> (Transaction tran = <span class="keyword">new</span> Transaction(doc, <span class="string">&quot;command2&quot;</span>))</span><br><span class="line">        &#123;</span><br><span class="line">            tran.Start();</span><br><span class="line">            doc.Delete(temCurve.Id);</span><br><span class="line">            tran.Commit();</span><br><span class="line">        &#125;</span><br><span class="line">        transactionGroup.RollBack();</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    uiapp.DialogBoxShowing -= Uiapp_DialogBoxShowing;</span><br><span class="line">    <span class="keyword">return</span> Result.Succeeded;</span><br><span class="line"></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">Uiapp_DialogBoxShowing</span>(<span class="params"><span class="built_in">object</span> sender,Autodesk.Revit.UI.Events.DialogBoxShowingEventArgs e</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    e.OverrideResult((<span class="built_in">int</span>)TaskDialogResult.Ok);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="参考资料"><a href="#参考资料" class="headerlink" title="参考资料"></a>参考资料</h2><p><a target="_blank" rel="noopener" href="https://blog.csdn.net/flower4wine/article/details/6838917">https://blog.csdn.net/flower4wine/article/details/6838917</a></p>
<p><a target="_blank" rel="noopener" href="https://thebuildingcoder.typepad.com/blog/2010/11/mirroring-in-a-new-family-and-changing-active-view.html">https://thebuildingcoder.typepad.com/blog/2010/11/mirroring-in-a-new-family-and-changing-active-view.html</a></p>

      
    </div>

    
    
    

    <footer class="post-footer">
        <div class="post-eof"></div>
      
    </footer>
  </article>
</div>




    


<div class="post-block">
  
  

  <article itemscope itemtype="http://schema.org/Article" class="post-content" lang="">
    <link itemprop="mainEntityOfPage" href="http://lisiting.net/2023/03/19/%E6%96%B0%E7%9A%84%E5%BC%80%E5%A7%8B/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="image" content="/images/avatar.gif">
      <meta itemprop="name" content="李有时">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="无佛处">
      <meta itemprop="description" content="Sometimes Blogging">
    </span>

    <span hidden itemprop="post" itemscope itemtype="http://schema.org/CreativeWork">
      <meta itemprop="name" content="undefined | 无佛处">
      <meta itemprop="description" content="">
    </span>
      <header class="post-header">
        <h2 class="post-title" itemprop="name headline">
          <a href="/2023/03/19/%E6%96%B0%E7%9A%84%E5%BC%80%E5%A7%8B/" class="post-title-link" itemprop="url">新的开始</a>
        </h2>

        <div class="post-meta-container">
          <div class="post-meta">
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-calendar"></i>
      </span>
      <span class="post-meta-item-text">发表于</span>
      

      <time title="创建时间：2023-03-19 02:16:47 / 修改时间：02:24:59" itemprop="dateCreated datePublished" datetime="2023-03-19T02:16:47+08:00">2023-03-19</time>
    </span>

  
</div>

        </div>
      </header>

    
    
    
    <div class="post-body" itemprop="articleBody">
          <p>多年的博客搞没了</p>
<p>没事，不就再来一把吗</p>
<p>东山再起没什么难的</p>
<p>别忘记自己的模样就好</p>

      
    </div>

    
    
    

    <footer class="post-footer">
        <div class="post-eof"></div>
      
    </footer>
  </article>
</div>





</div>
  </main>

  <footer class="footer">
    <div class="footer-inner">


<div class="copyright">
  &copy; 
  <span itemprop="copyrightYear">2023</span>
  <span class="with-love">
    <i class="fa fa-heart"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">李有时</span>
</div>
  <div class="powered-by">由 <a href="https://hexo.io/" rel="noopener" target="_blank">Hexo</a> & <a href="https://theme-next.js.org/" rel="noopener" target="_blank">NexT.Gemini</a> 强力驱动
  </div>

    </div>
  </footer>

  

<noscript>
  <div class="noscript-warning">Theme NexT works best with JavaScript enabled</div>
</noscript>


  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js" integrity="sha256-XL2inqUJaslATFnHdJOi9GfQ60on8Wx1C2H8DYiN1xY=" crossorigin="anonymous"></script>
<script src="/js/comments.js"></script><script src="/js/utils.js"></script><script src="/js/motion.js"></script><script src="/js/next-boot.js"></script>

  




  





</body>
</html>
